apiVersion: v1
kind: Pod
metadata:
  name: load-test-pod
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
  restartPolicy: Always
