apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hyperdisk-balanced-tpu
provisioner: pd.csi.storage.gke.io
parameters:
  type: hyperdisk-balanced
  # provisioned-iops: "3000" # Optional: Adjust IOPS as needed
  # provisioned-throughput: "140" # Optional: Adjust Throughput (MiB/s) as needed
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hd-claim
spec:
  storageClassName: hyperdisk-balanced-tpu
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-tpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-tpu
  template:
    metadata:
      labels:
        app: vllm-tpu
    spec:
      nodeSelector:
        cloud.google.com/gke-tpu-accelerator: tpu7x
        cloud.google.com/gke-tpu-topology: 1x1x1
      containers:
      - name: vllm-tpu
        image: vllm/vllm-tpu:ironwood
        command: ["python3", "-m", "vllm.entrypoints.openai.api_server"]
        args:
        - --host=0.0.0.0
        - --port=8000
        - --tensor-parallel-size=1
        - --max-model-len=3000
        - --download-dir=/data
        - --max-num-batched-tokens=2048
        - --max-num-seqs=128
        - --model=meta-llama/Llama-3.1-8B-Instruct
        env:
        - name: HF_HOME
          value: /data
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_api_token
        - name: TPU_BACKEND_TYPE
          value: jax
        ports:
        - containerPort: 8000
        resources:
          limits:
            google.com/tpu: '1'
          requests:
            google.com/tpu: '1'
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - mountPath: "/data"
          name: data-volume
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: data-volume
        persistentVolumeClaim:
          claimName: hd-claim
