apiVersion: apps/v1
kind: Deployment
metadata:
  name: gstreamer-test
spec:
  replicas: 24
  selector:
    matchLabels:
      app: gstreamer-test
  template:
    metadata:
      labels:
        app: gstreamer-test
    spec:
      serviceAccountName: gstreamer-sa
      nodeSelector:
        cloud.google.com/gke-nodepool: t4-r550-driver-pool-32
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: ui-streamer
        image: ${IMAGE_TAG}
        env:
        - name: GST_DEBUG
          value: "GST_STATES:5,nvh264enc:5"
        resources:
          limits:
            nvidia.com/gpu: 1
